server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vuduc870@gmail.com
    password: eijwsiwmppgvqdbz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://167.99.78.5:3306/childcare
    username: devbaoo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
